services:
  - type: web
    name: black-russia-boost-bot
    runtime: python
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 8618145300:AAEdkIkpY4G-a_dJx6NaD1YBHa_MQu_3ZwA
      - key: ADMIN_ID
        value: 8145260053
      - key: PORT
        value: 8080
    buildCommand: pip install -r requirements.txt
    startCommand: python byst.py
    healthCheckPath: /
